name: build-changelog-renovate-bot

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  add-updated-dependencies-to-changelog:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/build-changelog-renovate-bot.yaml@main
    with:
      gradle-cache-disabled: true
    secrets:
      TOKEN_GITHUB_ACTION: '${{ secrets.TOKEN_GITHUB_ACTION }}'
