name: publish-kotlin

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/publish-kotlin.yaml@34fd38844e1c27ceddc6f62d257f50a690843c22 # main
    with:
      code-quality-check: false
      publish-maven-central: false
      publish-gradle-plugin-portal: false
      publish-jetbrains-marketplace: true
      publish-docs: false
      publish-github-release: false
    secrets: inherit
