name: publish-kotlin

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/publish-kotlin.yaml@main
    with:
      publish-maven-central: false
      publish-gradle-plugin-portal: false
      publish-jetbrains-marketplace: true
      publish-docs: false
      publish-github-release: false
    secrets: inherit
